config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :viewer_accesses
  resources :profiles do
    resources :accessers
    resources :reviews
  end
  devise_for :users, :path_prefix => 'd'

  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :users, :only =>[:show]
  # do
  #   resources :reviews
  # end

  #devise_for :users
  #og, maybe add back!
  get 'welcome/index'

    resources :reviews do
      resources :comments
      #nested element of reviews, reinforces hierarchy
    end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_many :reviews, dependent: :destroy
  #has_many :viewer_accesses
  has_many :accessers, dependent: :destroy
  #has_many :users, through: :viewer_accesses


  # <%= User.find(profile.user_id).firstName %>
  # <%= User.find(profile.user_id).lastName %>
  # <%= User.find(profile.user_id).email %>

  def self.search(search)
    where("firstName LIKE ? OR lastName LIKE ? OR firstName OR (firstName || ' ' || lastName) LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    if params[:search]
      @profiles = Profile.search(params[:search])
    else
      @profiles = Profile.all
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @reviews = Review.where("profile_id = ?", params[:id])
    #@accessers = Accesser.where("profile_id = ?", params[:id])
  end

  # GET /profiles/new
  def new
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.build_profile(profile_params)
    # @profile.date = Time.now.strftime("%d/%m/%Y %H:%M")
    date = Time.now.strftime("%d/%m/%Y %H:%M")
    @profile.firstName = current_user.firstName
    @profile.lastName = current_user.lastName

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update


    profile = Profile.find(params[:id]) #gets profile id
    puts "this is"
    puts profile.user_id
    puts profile.id

    #user = User.find(params[:id])
    puts "curr user"
    puts current_user.id
    puts "checked"
    #
    # if profile.id != current_user.id
    #   puts "hello there"
    #   #authorize! :allow_access, @profile if params[:profile][:allow_access] end
    #   puts "authorized"
    #   respond_to do |format|
    #     if @profile.update(profile_param2)
    #       format.html { redirect_to(@profile) and return, notice: 'Profile was successfully updated.' }
    #       format.json { render :show, status: :ok, location: @profile }
    #     end
    #   end
    # end

    #need a way to find the right profile
    # @profile = Profile.find(11)
    #in the future, ideal that the profile id and user id same
    @profile = Profile.find(params[:id])
    # userId = @profile.user_id
    # lord = current_user
    # # @viewer = Viewer.new(params[:id])
    # # #access to me for user of current page
    # # Viewer.create(pageAccess: true, profile: lord, user: userId)
    #
    # @profile = Profile.find(lord)
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.fetch(:profile, {})
    end
    def profile_param2
      params.require(:profile).permit(:access_allowed)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: @profile, local: true) do |form| %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_new.html.erb
<%= link_to 'Leave a review!', new_review_path%>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td> <br>
      </tr>
      <%= User.find(profile.user_id).firstName %>
      <%= User.find(profile.user_id).lastName %>,
      <%= User.find(profile.user_id).email %>
    <% end %>
  </tbody>
</table>

<% if @profiles.blank? %>
  <h4>There are no users that match <%= params[:search] %>.</h4>
<% end %>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>


<% if can? :update, @profile %>
  <%= link_to "Edit", edit_profile_path(@profile) %>
<% end %>


<!-- <%= link_to 'create', new_review_path%> -->
<h1><%= User.find(@profile.user_id).firstName %> <%= User.find(@profile.user_id).lastName %></h1>


<% if current_user.id != @profile.user_id %>
<%= form_with(model: [@profile, @profile.accessers.build]) do |form| %>
  <%= form.label :allow_access %>
  <%= form.check_box :access_granted  %>
  <%= form.submit "enter", class: "btn btn-primary" %>
<% end %>
<% end %>

<% allowed = false %>
<% @accesser = Accesser.all  %>
<% @accesser.each do |viewer| %>


<% if viewer.viewing_id == current_user.id %>
<% if viewer.viewable_profile == @profile.user_id %>
  <%if viewer.access_granted %>
    <% allowed = true %>
  <%end%>
  <% end %>
  <% end %>
<% end %>

<% if current_user.id == @profile.user_id %>
<% allowed = true %>
<% end %>

<% reviewed = false %>
<% if allowed%>
<% @reviews.order('moveOut asc') %>
<% @reviews.each do |review| %>
    <h4> Review of <%= User.find(@profile.user_id).firstName %> <%= User.find(@profile.user_id).lastName %> by <%= User.find(review.user_id).firstName %> <%= User.find(review.user_id).lastName %> </h4>
    Reviewed on: <%= review.date %> <br>

    Proper notice given:
    <%= review.notice %> <br>
    Is tenant liable for rent or any unpaid amount:
    <%= review.rentLeft %> <br>
    Amount of unpaid rent:
    <%= review.rentLeftAmount %> <br>
    Any late payments or 3 day notices:
    <%= review.late %> <br>
    Amount of 3 day notices:
    <%= review.lateThreeDayNum %> <br>
    Amount of late payments:
    <%= review.latePaymentNum %> <br>
    Any NSF (non-sufficient funds) checks:
    <%= review.nSF %> <br>
    Amount of NSF checks:
    <%= review.nsfNum %> <br>
    Any documented damages:
    <%= review.damages %> <br>
    Damage description:
    <%= review.damagesDescription %> <br>
    Any documented complaints:
    <%= review.complaintsFiled %> <br>
    Complaint description:
    <%= review.complaintDescription %> <br>
    Any unauthorized tenants or pets:
    <%= review.undocumentedHousemates %> <br>
    Did tenant share with a co-tenant?
    <%= review.coTenants %> <br>
    Were they on a written rental agreement?
    <%= review.rentalStatus %> <br>
    Have they ever been asked to vacate?
    <%= review.evicted %> <br>
    Would you re-rent to them?
    <%= review.rentAgain %> <br>
    Was deposit refunded?
    <%= review.depositRefund %> <br>
    Do they have a pet?
    <%= review.pets %> <br>
    Pet type(s):
    <%= review.petType %> <br>
    What was the rent amount:
    <%= review.rentAmount %> <br>
    Were they on a lease:
    <%= review.lease %> <br>
    Additional notes on tenant:
    <%= review.tenantNotes %> <br>
    Move-in date:
    <%= review.moveIn %>
    <br>
    Move-out date:
    <%= review.moveOut %>
    <br>

    <br>

<% end %>

<% end %>

<% if current_user.id != @profile.user_id  %>


<%= render 'reviews/form', profile: @profile %>
<% end %>

<% if @profile.user_id == current_user.id %>
<% if reviewed == false%>
<br>
No reviews yet! Request a review from a previous landlord.
<% end %>
<% end %>