config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :viewer_accesses
  resources :profiles do
    resources :accessers
    resources :reviews
  end
  devise_for :users, :path_prefix => 'd'

  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :users, :only =>[:show]
  # do
  #   resources :reviews
  # end

  #devise_for :users
  #og, maybe add back!
  get 'welcome/index'

    resources :reviews do
      resources :comments
      #nested element of reviews, reinforces hierarchy
    end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # notice: "no yikes"
  #
  load_and_authorize_resource param_method: :reviews_params
  # notice: "yikes"
  #before_action :authenticate_user!
#controller for all review related actions for the form
  def index
    @review = Review.all
    #provide ALL the reivew "objects"
  end

  #display content
  def show
    @review = Review.find(params[:id])
    #pass in params[:id] to get the :id parameter from the request
  end

  def new
    @review = Review.new(params[:id])

  end

  def edit
    @review = Review.find(params[:id])
  end

  #create action for ruby stuff
  def create

    @profile = Profile.find(params[:profile_id])
    @review = @profile.reviews.build(reviews_params)
    @review.user_id = current_user.id

    @review.date = Time.now.strftime("%d/%m/%Y")
    date = Time.now.strftime("%d/%m/%Y")
    puts "DATE"
    puts date

    if @review.save!
      redirect_to @profile, notice: "Review saved, thank you!"
    else
      redirect_to @profile, notice: "Review was not saved, please check to see if all boxes are filled out."
    end
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(reviews_params)
      redirect_to @review
    else
      render 'edit'
    end
  end

  def destroy
  @review = Review.find(params[:id])
  @review.destroy

  redirect_to reviews_path
  end

  private
  def reviews_params
    params.require(:review).permit(:notice, :rentLeft, :rentLeftAmount,
      :late, :lateThreeDayNum, :latePaymentNum, :nSF, :nsfNum, :damages,
      :damagesDescription, :complaintsFiled, :complaintDescription,
      :undocumentedHousemates, :coTenants, :rentalStatus, :evicted,
      :rentAgain, :depositRefund, :pets, :petType, :rentAmount, :lease, :tenantNotes, :moveIn, :moveOut)
    #prevents wrongful assignment in database if fields off
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: [@profile, @profile.reviews.build]) do |form| %>
  <p>
    <%= form.label :Reviewer %><br>
    <%= current_user.firstName  %>
    <%= current_user.lastName %>
  </p>

  <p>
    <%= form.label :tenant %><br>
    <%= User.find(@profile.user_id).firstName %>
    <%= User.find(@profile.user_id).lastName %>
  </p>

  <p>

  </p>

  <ol>
    <li>
      <%= form.label :Proper_notice_given? %><br>
      <%= form.label :notice, "Yes", :value => "Yes"  %>
     <%= form.radio_button :notice, true%>
     <%= form.label :notice, "No", :value => "No" %>
     <%= form.radio_button :notice, false %>
   </li>

    <li>
      <%= form.label :Is_tenant_liable_for_rent_or_any_unpaid_amount? %><br>
      <%= form.label :rentLeft, "Yes", :value => "Yes"  %>
      <%= form.radio_button :rentLeft, true%>
      <%= form.label :rentLeft, "No", :value => "No" %>
      <%= form.radio_button :rentLeft, false %>
    </li>

    <p>
      <%= form.label :Enter_amount_of_unpaid_rent %><br>
      <%= form.number_field :rentLeftAmount %>
    </p>

    <li>
      <%= form.label :Any_late_payments_or_3_day_notices? %><br>
      <%= form.label :late, "Yes", :value => "Yes"  %>
      <%= form.radio_button :late, true%>
      <%= form.label :late, "No", :value => "No" %>
      <%= form.radio_button :late, false %>
    </li>

    <p>
      <%= form.label :Enter_amount_of_3_day_notices %><br>
      <%= form.number_field :lateThreeDayNum %>
    </p>

    <p>
      <%= form.label :Enter_amount_of_late_payments %><br>
      <%= form.number_field :latePaymentNum %>
    </p>

    <li>
      <%= form.label :Any_NSF_checks? %><br>
      <%= form.label :nSF, "Yes", :value => "Yes"  %>
      <%= form.radio_button :late, true%>
      <%= form.label :nSF, "No", :value => "No" %>
      <%= form.radio_button :nSF, false %>
    </li>

    <p>
      <%= form.label :Enter_amount_of_NSF_checks %><br>
      <%= form.number_field :nsfNum %>
    </p>

    <li>
      <%= form.label :Any_documented_damages? %><br>
      <%= form.label :damages, "Yes", :value => "Yes"  %>
      <%= form.radio_button :damages, true%>
      <%= form.label :damages, "No", :value => "No" %>
      <%= form.radio_button :damages, false %>
    </li>

    <p>
      <%= form.label :Please_explain %><br>
      <%= form.text_field :damagesDescription %>
    </p>

    <li>
      <%= form.label :Any_documented_complaints? %><br>
      <%= form.label :complaintsFiled, "Yes", :value => "Yes"  %>
      <%= form.radio_button :complaintsFiled, true%>
      <%= form.label :complaintsFiled, "No", :value => "No" %>
      <%= form.radio_button :complaintsFiled, false %>
    </li>

    <p>
      <%= form.label :Please_explain %><br>
      <%= form.text_field :complaintDescription %>
    </p>

    <li>
      <%= form.label :Any_unauthorized_tenants_or_pets? %><br>
      <%= form.label :undocumentedHousemates, "Yes", :value => "Yes"  %>
      <%= form.radio_button :undocumentedHousemates, true%>
      <%= form.label :undocumentedHousemates, "No", :value => "No" %>
      <%= form.radio_button :undocumentedHousemates, false %>
    </li>

    <li>
      <%= form.label :Did_tenant_share_with_a_co_tenant? %><br>
      <%= form.label :coTenants, "Yes", :value => "Yes"  %>
      <%= form.radio_button :coTenants, true%>
      <%= form.label :coTenants, "No", :value => "No" %>
      <%= form.radio_button :coTenants, false %>
    </li>

    <li>
      <%= form.label :Were_they_on_a_written_rental_agreement? %><br>
      <%= form.label :rentalStatus, "Yes", :value => "Yes"  %>
      <%= form.radio_button :rentalStatus, true%>
      <%= form.label :rentalStatus, "No", :value => "No" %>
      <%= form.radio_button :rentalStatus, false %>
    </li>

    <li>
      <%= form.label :Has_tenant_ever_been_asked_to_vacate? %><br>
      <%= form.label :evicted, "Yes", :value => "Yes"  %>
      <%= form.radio_button :evicted, true%>
      <%= form.label :evicted, "No", :value => "No" %>
      <%= form.radio_button :evicted, false %>
    </li>

    <li>
      <%= form.label :Would_you_rent_to_them_again? %><br>
      <%= form.label :rentAgain, "Yes", :value => "Yes"  %>
      <%= form.radio_button :rentAgain, true%>
      <%= form.label :rentAgain, "No", :value => "No" %>
      <%= form.radio_button :rentAgain, false %>
    </li>

    <li>
      <%= form.label :Was_deposit_refunded? %><br>
      <%= form.label :depositRefund, "Yes", :value => "Yes"  %>
      <%= form.radio_button :depositRefund, true%>
      <%= form.label :depositRefund, "No", :value => "No" %>
      <%= form.radio_button :depositRefund, false %>
    </li>

    <li>
      <%= form.label :Do_they_have_a_pet? %><br>
      <%= form.label :pets, "Yes", :value => "Yes"  %>
      <%= form.radio_button :pets, true%>
      <%= form.label :pets, "No", :value => "No" %>
      <%= form.radio_button :pets, false %>
    </li>

    <p>
      <%= form.label :Enter_pet_type_or_types %><br>
      <%= form.text_field :petType %>
    </p>

    <li>
      <%= form.label :What_was_the_rent_amount? %><br>
      <%= form.number_field :rentAmount %>
    </li>

    <li>
      <%= form.label :Were_they_on_a_lease? %><br>
      <%= form.label :lease, "Yes", :value => "Yes"  %>
      <%= form.radio_button :lease, true%>
      <%= form.label :lease, "No", :value => "No" %>
      <%= form.radio_button :lease, false %>
    </li>


    <p>
      <%= form.label :Any_additional_notes_on_this_tenant? %><br>
      <%= form.text_area :tenantNotes %>
    </p>

    <p>
      <%= form.label :Tenant_move_in_date %><br>
      <%= form.date_field :moveIn %>
    </p>

    <p>
      <%= form.label :Tenant_move_out_date %><br>
      <%= form.date_field :moveOut %>
    </p>



  </ol>

    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/reviews/_new.html.erb
<%= link_to 'Leave a review!', create_review_path(@profile)%>

app/views/reviews/edit.html.erb
<h1>Edit review!!</h1>

<%= render 'form' %>

<%= link_to 'back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>
<!-- MAKE SHOW BASED ON WHO IS SIGNED IN -->
<%= link_to 'New review!', new_review_path %>
<table>
  <tr>
    <th>reviewer</th>
    <th>
    <th>reviewed</th>
  </tr>

  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.user_id %></td>
    
      <td><%= review.profile_id %></td>

      <td><%= link_to 'Show', review_path(review) %></td>
      <td><%= link_to 'Edit', edit_review_path(review) %></td>
      <td><%= link_to 'Delete', review_path(review), method: :delete, data: {confirm: 'Are you sure you want to delete this review?'}%></td>
    </tr>
  <% end %>
</table>

app/views/reviews/new.html.erb
<h1>New review!</h1>

<%= render 'form', profile: @profile  %>

<%= link_to 'move back', reviews_path %>

app/views/reviews/show.html.erb
<p>
  <strong>num:</strong>
  <%= @review.rentLeftAmount %>
</p>

Reviewed on: <%= @review.date %> <br>

Proper notice given:
<%= @review.notice %> <br>
Is tenant liable for rent or any unpaid amount:
<%= @review.rentLeft %> <br>
Amount of unpaid rent:
<%= @review.rentLeftAmount %> <br>
Any late payments or 3 day notices:
<%= @review.late %> <br>
Amount of 3 day notices:
<%= @review.lateThreeDayNum %> <br>
Amount of late payments:
<%= @review.latePaymentNum %> <br>
Any NSF (non-sufficient funds) checks:
<%= @review.nSF %> <br>
Amount of NSF checks:
<%= @review.nsfNum %> <br>
Any documented damages:
<%= @review.damages %> <br>
Damage description:
<%= @review.damagesDescription %> <br>
Any documented complaints:
<%= @review.complaintsFiled %> <br>
Complaint description:
<%= @review.complaintDescription %> <br>
Any unauthorized tenants or pets:
<%= @review.undocumentedHousemates %> <br>
Did tenant sahre with a co-tenant?
<%= @review.coTenants %> <br>
Were they on a written rental agreement?
<%= @review.rentalStatus %> <br>
Have they ever been asked to vacate?
<%= @review.evicted %> <br>
Would you re-rent to them?
<%= @review.rentAgain %> <br>
Was deposit refunded?
<%= @review.depositRefund %> <br>
Do they have a pet?
<%= @review.pets %> <br>
Pet type(s):
<%= @review.petType %> <br>
What was the rent amount:
<%= @review.rentAmount %> <br>
Were they on a lease:
<%= @review.lease %> <br>
Additional notes on tenant:
<%= @review.tenantNotes %> <br>
Move-in date:
<%= @review.moveIn %>
<br>
Move-out date:
<%= @review.moveOut %>
<br>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>