config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :viewer_accesses
  resources :profiles do
    resources :accessers
    resources :reviews
  end
  devise_for :users, :path_prefix => 'd'

  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :users, :only =>[:show]
  # do
  #   resources :reviews
  # end

  #devise_for :users
  #og, maybe add back!
  get 'welcome/index'

    resources :reviews do
      resources :comments
      #nested element of reviews, reinforces hierarchy
    end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/viewer_accesses_controller.rb
class ViewerAccessesController < ApplicationController
  before_action :set_viewer_access, only: [:show, :edit, :update, :destroy]

  # GET /viewer_accesses
  # GET /viewer_accesses.json
  # def create
  # end
  #
  # def destroy
  # end

  def index
    @viewer_accesses = ViewerAccess.all
  end

  # GET /viewer_accesses/1
  # GET /viewer_accesses/1.json
  def show
    @viewer_accesses = ViewerAccess.where("profile_id = ?", params[:id])

  end

  # GET /viewer_accesses/new
  def new
    #@viewer_access = ViewerAccess.new()
    @viewer_access = current_user.build_viewer_access
  end

  # GET /viewer_accesses/1/edit
  def edit
  end

  # POST /viewer_accesses
  # POST /viewer_accesses.json
  def create
    #@viewer_access = ViewerAccess.new(viewer_access_params2)
    #@viewer_access = current_user.build_current_user(viewer_access_params2)
    #new attempt
    @profile = Profile.find(params[:profile_id])
    @viewer_access = @profile.viewer_accesses.build(viewer_access_params2)
    @viewer_access.viewer_access = current_user.id

    puts "SHIT WAS MADE"
    respond_to do |format|
      if @viewer_access.save
        puts "SHIT REAAALY MADE"
        format.html { redirect_to @profile, notice: 'Viewer access was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        redirect_to @profile, notice: "couldn't save viewer access"
      #   format.html { render :new }
      #   format.json { render json: @profile.errors, status: :unprocessable_entity }
      #
     end
    end
  end

  # PATCH/PUT /viewer_accesses/1
  # PATCH/PUT /viewer_accesses/1.json
  def update
    #authorize! :access_given, @profile if params[:profile][:access_given]

    respond_to do |format|
      if @viewer_access.update(viewer_access_params2)
        format.html { redirect_to @viewer_access, notice: 'Viewer access was successfully updated.' }
        format.json { render :show, status: :ok, location: @viewer_access }
      else
        format.html { render :edit }
        format.json { render json: @viewer_access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /viewer_accesses/1
  # DELETE /viewer_accesses/1.json
  def destroy
    @viewer_access.destroy
    respond_to do |format|
      format.html { redirect_to viewer_accesses_url, notice: 'Viewer access was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_viewer_access
      @viewer_access = ViewerAccess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def viewer_access_params
      params.fetch(:viewer_access, {})
    end
    def viewer_access_params2
      params.require(:viewer_access).permit(:viewing_id, :viewable_profile, :access_given)
    end
end

app/helpers/viewer_accesses_helper.rb
module ViewerAccessesHelper
end

app/views/viewer_accesses/_form.html.erb
<%= form_with(model: viewer_access, local: true) do |form| %>



<%= form.label :viewer %>
<%= form.number_field :viewing_id %>
<br>
<%= form.label :viewable %>
<%= form.number_field :viewable_profile %>
<br>
<%= form.label :allow_access %>
<%= form.check_box :access_given  %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/viewer_accesses/edit.html.erb
<h1>Editing Viewer Access</h1>

<%= render 'form', viewer_access: @viewer_access %>

<%= link_to 'Show', @viewer_access %> |
<%= link_to 'Back', viewer_accesses_path %>

app/views/viewer_accesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Viewer Accesses!</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @viewer_accesses.each do |viewer_access| %>
      <tr>
        <td>viewer: <%= viewer_access.viewing_id %></td>
        <td>viewable: <%= viewer_access.viewable_profile %></td>
        <td><%= link_to 'Show', viewer_access %></td>
        <td><%= link_to 'Edit', edit_viewer_access_path(viewer_access) %></td>
        <td><%= link_to 'Destroy', viewer_access, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Viewer Access', new_viewer_access_path %>

app/views/viewer_accesses/new.html.erb
<h1>New Viewer Access</h1>

<%= render 'form', viewer_access: @viewer_access %>

<%= link_to 'Back', viewer_accesses_path %>

app/views/viewer_accesses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_viewer_access_path(@viewer_access) %> |
<%= link_to 'Back', viewer_accesses_path %>