config/routes.rb
Rails.application.routes.draw do
  resources :abouts
  resources :viewer_accesses
  resources :profiles do
    resources :accessers
    resources :reviews
  end
  devise_for :users, :path_prefix => 'd'

  get 'users/index'
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :users, :only =>[:show]
  # do
  #   resources :reviews
  # end

  #devise_for :users
  #og, maybe add back!
  get 'welcome/index'

    resources :reviews do
      resources :comments
      #nested element of reviews, reinforces hierarchy
    end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, Profile
        can :create, Profile
        #can :update, Profile, user_id: user.id
        can :create, Profile
        can :update, Profile, user_id:user.id
        can :destroy, Profile, user_id: user.id
      #  can :access_given, ViewerAccess, user_id: user.id
        #can :read, Profile, user_id: user.id
        can :manage, ViewerAccess
        can :read, Review
        can :create, Review, user_id: user.id
        can :edit, Review, user_id: user.id
        can :destroy, Review, user_id: user.id
        #can :read, Review, user_id: user.id
        #can :read, Review, user_id: 11
        #if review.user_id matches user.id of passed in user, they can
        #can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :profile
  belongs_to :user
end

app/models/accesser.rb
class Accesser < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  #sets up an Active Record association
  #creates a new column on your database table with the provided model name appended with an id
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_many :reviews, dependent: :destroy
  #has_many :viewer_accesses
  has_many :accessers, dependent: :destroy
  #has_many :users, through: :viewer_accesses


  # <%= User.find(profile.user_id).firstName %>
  # <%= User.find(profile.user_id).lastName %>
  # <%= User.find(profile.user_id).email %>

  def self.search(search)
    where("firstName LIKE ? OR lastName LIKE ? OR firstName OR (firstName || ' ' || lastName) LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/models/review.rb
class Review < ApplicationRecord #//inherets from
  belongs_to :user
  belongs_to :profile #the tenant reviewed
  #validates :user_id, presence: true
  #validates :profile_id, presence: true
  # validates :notice, presence: true
  # validates_inclusion_of :notice, in: ["true", "false"]
  # validates :rentLeft, presence: true
  # validates_inclusion_of :rentLeft, in: ["true", "false"]

  # if :rentLeft
  #   validates :rentLeftAmount, presence: true, length: { minimum: 1 }
  # end
  # validates :late, presence: true
  # if :late
  #   validates :lateThreeDayNum, presence: true, length: { minimum: 1 }
  #   validates :latePaymentNum, presence: true, length: { minimum: 1 }
  # end
  # validates :nSF, presence: true
  # if :nSF
  #  validates :nsfNum, presence: true, length: { minimum: 1 }
  # end
  # validates :damages, presence: true
  # if :damages
  #  validates :damagesDescription, presence: true
  # end
  # validates :complaintsFiled, presence: true
  # if :complaintsFiled
  #  validates :complaintDescription, presence: true
  # end
  # validates :undocumentedHousemates, presence: true
  # validates :coTenants, presence: true
  # validates :rentalStatus, presence: true
  # validates :evicted, presence: true
  # validates :rentAgain, presence: true
  # validates :depositRefund, presence: true
  # validates :pets, presence: true
  # if :pets
  #   validates :petType, presence: true
  # end
  # validates :rentAmount, presence: true, length: { minimum: 1 }
  # validates :lease, presence: true
  # validates :moveIn, presence: true
  # validates :moveOut, presence: true



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :accessers, dependent: :destroy
  #has_many :profiles, through: :viewer_accesses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :confirmable,
  #        :recoverable, :rememberable, :trackable, :validatable


  # don't think we need this twice, but left it commented just in case!! - Lucca
  # # Include default devise modules. Others available are:
  # # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :confirmable,
  #        :recoverable, :rememberable, :trackable, :validatable

end

app/models/viewer.rb
class Viewer < ApplicationRecord
  belongs_to :user
  belongs_to :profile
end

app/models/viewer_access.rb
class ViewerAccess < ApplicationRecord
  belongs_to :profile
  belongs_to :user
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/accessers_helper.rb
module AccessersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/viewers_helper.rb
module ViewersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Renter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>

                                          <!--[if lt IE 9]>
                                            <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
                                            </script>
                                          <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "renter", welcome_index_path, id: "logo" %>


        <nav>
          <ul class="nav navbar-nav navbar-right">

            <!-- Search bar -->
            <%= form_tag(profiles_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
              <%= submit_tag "Search", :name => nil %>
            <% end %>



            <li><%= link_to "About", abouts_path %></li>
            <!-- <li><%= link_to "About", welcome_index_path %></li> -->

            <!-- if not signed in-->
            <!-- <li><%= link_to "Log in", new_user_registration_path %></li> -->
            <!-- if signed in -->
            <!-- <% if user_signed_in? %><li><%= link_to "Profile", '#' %></li>
            <% else %><li><%= link_to "Log in", new_user_registration_path %></li><%end%> -->

            <% if user_signed_in? %>
              <%if current_user.profile == nil %>
                <li><%= link_to 'Create profile', new_profile_path%></li>
              <% else %>
                <li><%= link_to 'View your profile', current_user.profile%></li>
              <% end %>
              <li><%= link_to 'Log out', destroy_user_session_path, :method=> 'delete'%></li>

            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <%end%>
            <!-- <% if user_signed_in? %>
              <li><% link_to 'Users', '#' %></li>
            <%end%> -->
            <!-- don't require log in, show profile -->
            <!-- <li><%= link_to "Profile", '#'%> </li> -->

          </ul>
        </nav>
      </div>
    </header>
    <!-- <% if user_signed_in? %>
      <%= current_user.firstName %> <%= current_user.lastName %>
    <% end %> -->
    <div class="container">
    <!-- #keep or move up? -->
    <% if notice %> <p class="alert alert-info"><%= notice%> <%end%></p>
    <% if alert %><p class="alert alert-warning"><%= alert %><%end%></p>
    <%= yield %>
  </body>
</html>